default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: test
  password: test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: growbox_backend_development

test:
  <<: *default
  database: growbox_backend_test

production:
  <<: *default
  database: growbox_backend_production
